# Assignment 4

Before working on this assignment please read these instructions fully. In the submission area, you will notice that you can click the link to **Preview the Grading** for each step of the assignment. This is the criteria that will be used for peer grading. Please familiarize yourself with the criteria before beginning the assignment.

This assignment requires that you to find **at least** two datasets on the web which are related, and that you visualize these datasets to answer a question with the broad topic of **weather phenomena** (see below) for the region of **St Petersburg, St.-Petersburg, Russia**, or **Russia** more broadly.

You can merge these datasets with data from different regions if you like! For instance, you might want to compare **St Petersburg, St.-Petersburg, Russia** to Ann Arbor, USA. In that case at least one source file must be about **St Petersburg, St.-Petersburg, Russia**.

You are welcome to choose datasets at your discretion, but keep in mind **they will be shared with your peers**, so choose appropriate datasets. Sensitive, confidential, illicit, and proprietary materials are not good choices for datasets for this assignment. You are welcome to upload datasets of your own as well, and link to them using a third party repository such as github, bitbucket, pastebin, etc. Please be aware of the Coursera terms of service with respect to intellectual property.

Also, you are welcome to preserve data in its original language, but for the purposes of grading you should provide english translations. You are welcome to provide multiple visuals in different languages if you would like!

As this assignment is for the whole course, you must incorporate principles discussed in the first week, such as having as high data-ink ratio (Tufte) and aligning with Cairo’s principles of truth, beauty, function, and insight.

Here are the assignment instructions:

 * State the region and the domain category that your data sets are about (e.g., **St Petersburg, St.-Petersburg, Russia** and **weather phenomena**).
 * You must state a question about the domain category and region that you identified as being interesting.
 * You must provide at least two links to available datasets. These could be links to files such as CSV or Excel files, or links to websites which might have data in tabular form, such as Wikipedia pages.
 * You must upload an image which addresses the research question you stated. In addition to addressing the question, this visual should follow Cairo's principles of truthfulness, functionality, beauty, and insightfulness.
 * You must contribute a short (1-2 paragraph) written justification of how your visualization addresses your stated research question.

What do we mean by **weather phenomena**?  For this category you might want to consider seasonal changes, natural disasters, or historical trends.

## Tips
* Wikipedia is an excellent source of data, and I strongly encourage you to explore it for new data sources.
* Many governments run open data initiatives at the city, region, and country levels, and these are wonderful resources for localized data sources.
* Several international agencies, such as the [United Nations](http://data.un.org/), the [World Bank](http://data.worldbank.org/), the [Global Open Data Index](http://index.okfn.org/place/) are other great places to look for data.
* This assignment requires you to convert and clean datafiles. Check out the discussion forums for tips on how to do this from various sources, and share your successes with your fellow students!

## Example
Looking for an example? Here's what our course assistant put together for the **Ann Arbor, MI, USA** area using **sports and athletics** as the topic. [Example Solution File](./readonly/Assignment4_example.pdf)

# F1 analysis

## 1 Region and Domain

Formula One (also Formula 1 or F1) is the highest class of single-seater international auto racing.
Thus, Formula One region is worldwide and Formula 1 is related to the autosport.

https://en.wikipedia.org/wiki/Formula_One

## 2 Research Question

What is amount of total races, amount of wins and home country for the pilots, who won Formula 1 at least once.

Pilots from which country trends to be more successfull in terms of relationship of wins to amount of finished races?

## 3 Links

Whole dataset used in the assignment is represented by user https://www.kaggle.com/cjgdev 

Used dataset has a following link :
https://www.kaggle.com/cjgdev/formula-1-race-data-19502017/data

In the current assignment following csv tables were used:
• 
•
•

## 4 Image

You must upload an image which addresses the research question you stated. In addition to addressing
the question, this visual should follow Cairo’s principles of truthfulness, functionality,
beauty, and insightfulness.

## 5 Discussion

You must contribute a short (1-2 paragraph) written justification of how your visualization
addresses your stated research question.
This visualization was concerned with answering the question of how the win percentages of the four
major Detroit sports teams (The Detroit Pistons, The Red Wings, The Detroit Tigers, and The Detroit
Lions) have changed over the last 40 years. Wikipedia was scraped for data concerning wins and losses
by season for each team. Any tie games were dropped from the analysis in order to provide a more
level comparison between the sports. A 10 year moving average was plotted to help the reader identify
any major trends in the team’s win percentages.

The plot indicates years of high win percentage for The Detroit Pistons around 1990 and 2005,
with periods of decline following both high points. The Detroit Red Wings’ win percentage shows an
increase in the 1990’s and stays high through the early 2000’s, with a downward trend in recent years.
The Detroit Tiger’s win percentage shows less variation than the other teams, hovering around 50%,
with it’s lowest win percentage in the early 2000’s. The win percentage of the Detroit Lions shows low
levels throughout the early 2000’s, with an increase after 2010

# Code

### Introducing the initial data

In [1]:
import os
import pandas as pd
import glob

In [2]:
path =r'C:\WorkData\GitStaff\Applied Data Science with Python\Course2\f1data'
all_files = glob.glob(os.path.join(path, "*.csv")) #make list of paths

filenames = []
filecontent = []
for file in all_files:
    file_name = os.path.splitext(os.path.basename(file))[0]
    filenames.append(file_name)
    dfn = pd.read_csv(file, encoding='latin1') #encoding='latin1', #encoding='iso-8859-1' #encoding='cp1252'
    filecontent.append(dfn)

print(filenames)

['circuits', 'constructorResults', 'constructors', 'constructorStandings', 'countries', 'drivers', 'driverStandings', 'lapTimes', 'pitStops', 'qualifying', 'races', 'results', 'seasons', 'status']

In [3]:
circuits = filecontent[0]
circuits.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,NaN,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,NaN,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,MontmelÌ_,Spain,41.57000,2.26111,NaN,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,NaN,http://en.wikipedia.org/wiki/Istanbul_Park

In [4]:
constructorResults = filecontent[1]
constructorResults.head()

   constructorResultsId  raceId  constructorId  points status
0                     1      18              1    14.0    NaN
1                     2      18              2     8.0    NaN
2                     3      18              3     9.0    NaN
3                     4      18              4     5.0    NaN
4                     5      18              5     2.0    NaN

In [5]:
constructors = filecontent[2]
constructors = constructors.drop(columns = ['Unnamed: 5','constructorRef','url','nationality'])
constructors.head()

   constructorId        name
0              1     McLaren
1              2  BMW Sauber
2              3    Williams
3              4     Renault
4              5  Toro Rosso

In [6]:
constructorStandings = filecontent[3]
constructorStandings.head()

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins,Unnamed: 7
0,1,18,1,14.0,1,1,1,NaN
1,2,18,2,8.0,3,3,0,NaN
2,3,18,3,9.0,2,2,0,NaN
3,4,18,4,5.0,4,4,0,NaN
4,5,18,5,2.0,5,5,0,NaN

In [7]:
drivers = filecontent[5]
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,NaN,HEI,Nick,Heidfeld,10/05/1977,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6.0,ROS,Nico,Rosberg,27/06/1985,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14.0,ALO,Fernando,Alonso,29/07/1981,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,NaN,KOV,Heikki,Kovalainen,19/10/1981,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [8]:
driverStandings = filecontent[6]
driverStandings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [9]:
lapTimes = filecontent[7]
lapTimes.head()

   raceId  driverId  lap  position      time  milliseconds
0     841        20    1         1  1:38.109         98109
1     841        20    2         1  1:33.006         93006
2     841        20    3         1  1:32.713         92713
3     841        20    4         1  1:32.803         92803
4     841        20    5         1  1:32.342         92342

In [10]:
pitStops = filecontent[8]
pitStops.head()

   raceId  driverId  stop  lap      time duration  milliseconds
0     841       153     1    1  17:05:23   26.898         26898
1     841        30     1    1  17:05:52   25.021         25021
2     841        17     1   11  17:20:48   23.426         23426
3     841         4     1   12  17:22:34   23.251         23251
4     841        13     1   13  17:24:10   23.842         23842

In [11]:
qualifying = filecontent[9]
qualifying.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [12]:
races = filecontent[10]
racesDate = races[['raceId', 'date' ,'name']]
racesDate = racesDate.rename({'name': 'Track'}, axis=1)
racesDate.head()

   raceId        date                  Track
0       1  2009-03-29  Australian Grand Prix
1       2  2009-04-05   Malaysian Grand Prix
2       3  2009-04-19     Chinese Grand Prix
3       4  2009-04-26     Bahrain Grand Prix
4       5  2009-05-10     Spanish Grand Prix

In [13]:
results = filecontent[11]
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22.0,1,1.0,1,1,10.0,58,34:50.6,5690616.0,39.0,2.0,01:27.5,218.3,1
1,2,18,2,2,3.0,5,2.0,2,2,8.0,58,5.478,5696094.0,41.0,3.0,01:27.7,217.586,1
2,3,18,3,3,7.0,7,3.0,3,3,6.0,58,8.163,5698779.0,41.0,5.0,01:28.1,216.719,1
3,4,18,4,4,5.0,11,4.0,4,4,5.0,58,17.181,5707797.0,58.0,7.0,01:28.6,215.464,1
4,5,18,5,1,23.0,3,5.0,5,5,4.0,58,18.014,5708630.0,43.0,1.0,01:27.4,218.385,1

In [14]:
seasons = filecontent[12]
seasons.head()

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

In [15]:
status = filecontent[13]
status.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [16]:
for l in range(len(filecontent)):
    print(filenames[l], len(filecontent[l]))

circuits 73
constructorResults 11142
constructors 208
constructorStandings 11896
countries 124
drivers 842
driverStandings 31726
lapTimes 426633
pitStops 6251
qualifying 7516
races 997
results 23777
seasons 69
status 134

### Modyfying the introduced datasets in order to show only winner results

In [17]:
import numpy as np

#driverStandingsWin = driverStandings.groupby('driverId', as_index=False)['wins'].sum()#.max()#.count()
#driverStandingsWin

Winners = results.loc[results['positionOrder'] == 1]
WinnersModified = Winners.copy()
WinnersModified = WinnersModified.drop(columns = ['laps','time', 'milliseconds', 'fastestLap', 'fastestLapTime', 'fastestLapSpeed','positionText','positionOrder','rank','points'])
WinnersModified.head()

,resultId,raceId,driverId,constructorId,number,grid,position,statusId
0,1,18,1,1,22.0,1,1.0,1
22,23,19,8,6,1.0,2,1.0,1
44,45,20,13,6,2.0,2,1.0,1
66,67,21,8,6,1.0,1,1.0,1
88,89,22,13,6,2.0,1,1.0,1

In [18]:
DriversWinAmount = Winners.groupby('driverId', as_index=False)['position'].sum()
DriversWinAmount.sort_values(['position'], axis=0, ascending=False, inplace = True)
DriversWinAmount.rename(columns = {'position' : 'TotalWins'}, inplace = True)
DriversWinAmount.head()

    driverId  TotalWins
15        30       91.0
0          1       62.0
29       117       51.0
11        20       47.0
27       102       41.0

In [19]:
#Winners = DriversWinAmount.merge(Winners, how='inner')
WinnersModified = WinnersModified.merge(DriversWinAmount, how='inner')
WinnersModified.head()

,resultId,raceId,driverId,constructorId,number,grid,position,statusId,TotalWins
0,1,18,1,1,22.0,1,1.0,1,62.0
1,109,23,1,1,22.0,3,1.0,1,62.0
2,169,26,1,1,22.0,4,1.0,1,62.0
3,189,27,1,1,22.0,1,1.0,1,62.0
4,329,34,1,1,22.0,1,1.0,1,62.0

In [20]:
drivers = drivers[['driverId', 'nationality', 'dob','forename','surname']]
drivers.head()

   driverId nationality         dob  forename     surname
0         1     British  07/01/1985     Lewis    Hamilton
1         2      German  10/05/1977      Nick    Heidfeld
2         3      German  27/06/1985      Nico     Rosberg
3         4     Spanish  29/07/1981  Fernando      Alonso
4         5     Finnish  19/10/1981    Heikki  Kovalainen

In [21]:
countries = filecontent[4]
countries.drop(['ISO','Country'], axis=1, inplace = True)
countries.rename(columns = {'Nationality' : 'nationality'}, inplace = True)
countries.head()

  Code nationality
0   AD    Andorian
1   AE     Emirian
2   AF     Afghani
3   AI   Anguillan
4   AM    Armenian

In [22]:
WinnersModified = drivers.merge(WinnersModified, how='inner')
WinnersModified = WinnersModified.merge(countries, how ='inner')
WinnersModified = WinnersModified.merge(constructors, how ='inner')
WinnersModified = racesDate.merge(WinnersModified, how ='inner')
WinnersModified.head()

,raceId,date,Track,driverId,nationality,dob,forename,surname,resultId,constructorId,number,grid,position,statusId,TotalWins,Code,name
0,1,2009-03-29,Australian Grand Prix,18,British,19/01/1980,Jenson,Button,7554,23,22.0,1,1.0,1,15.0,GB,Brawn
1,2,2009-04-05,Malaysian Grand Prix,18,British,19/01/1980,Jenson,Button,7574,23,22.0,1,1.0,1,15.0,GB,Brawn
2,3,2009-04-19,Chinese Grand Prix,20,German,03/07/1987,Sebastian,Vettel,7594,9,15.0,1,1.0,1,47.0,DE,Red Bull
3,4,2009-04-26,Bahrain Grand Prix,18,British,19/01/1980,Jenson,Button,7614,23,22.0,4,1.0,1,15.0,GB,Brawn
4,5,2009-05-10,Spanish Grand Prix,18,British,19/01/1980,Jenson,Button,7634,23,22.0,1,1.0,1,15.0,GB,Brawn

In [23]:
WinnersModified = WinnersModified.drop(columns = ['raceId','resultId','constructorId','number','statusId'])

In [24]:
WinnersModified.head()

,date,Track,driverId,nationality,dob,forename,surname,grid,position,TotalWins,Code,name
0,2009-03-29,Australian Grand Prix,18,British,19/01/1980,Jenson,Button,1,1.0,15.0,GB,Brawn
1,2009-04-05,Malaysian Grand Prix,18,British,19/01/1980,Jenson,Button,1,1.0,15.0,GB,Brawn
2,2009-04-19,Chinese Grand Prix,20,German,03/07/1987,Sebastian,Vettel,1,1.0,47.0,DE,Red Bull
3,2009-04-26,Bahrain Grand Prix,18,British,19/01/1980,Jenson,Button,4,1.0,15.0,GB,Brawn
4,2009-05-10,Spanish Grand Prix,18,British,19/01/1980,Jenson,Button,1,1.0,15.0,GB,Brawn

In [25]:
WinnersModified['date'] = pd.to_datetime(WinnersModified['date'])

In [26]:
#Drivers with more amount of accidents quit the f1 earlier than drivers with less amount of accidents
dfAccidents = results[['resultId', 'raceId', 'driverId', 'constructorId','laps', 'statusId']]

#exceptionlaps = [1,range(11,19)]
exceptions1 = [x for x in range(11,20)]
exceptions2 = [1,45,50,128,53,55,58,88,122,123,124,125,127,133,134]
exceptions3 = [x for x in range(111,121)]
exceptions = exceptions1 + exceptions2 + exceptions3


RaceIsNotFinished = dfAccidents.loc[~dfAccidents['statusId'].isin(exceptions)]
RaceIsFinished = dfAccidents.loc[dfAccidents['statusId'].isin(exceptions)]

RaceIsFinishedLaps = RaceIsFinished.groupby('driverId').count()['raceId'].copy()
RaceIsFinishedLaps.sort_values(ascending=False, inplace = True)

RaceIsNotFinishedLaps = RaceIsNotFinished.groupby('driverId').count()['raceId'].copy()
RaceIsNotFinishedLaps.sort_values(ascending=False, inplace = True)

RaceTotal = dfAccidents.groupby('driverId').count()['raceId'].copy()
RaceTotal.sort_values(ascending=False, inplace = True)

result = pd.concat([RaceIsFinishedLaps.rename('FinishedRaces'), RaceIsNotFinishedLaps.rename('NotFinishedRaces'), RaceTotal.rename('TotalRaces')], axis=1)
result.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)
result.reset_index(inplace = True)
result.head()

   driverId  FinishedRaces  NotFinishedRaces  TotalRaces
0         1          183.0              25.0         208
1         2          135.0              49.0         184
2         3          175.0              31.0         206
3         4          233.0              60.0         293
4         5           89.0              23.0         112

In [41]:
Winners = WinnersModified.merge(result, how='inner')
Winners.drop_duplicates(subset='dob', keep='first', inplace=True)
Winners

,date,Track,driverId,nationality,dob,forename,surname,grid,position,TotalWins,Code,name,FinishedRaces,NotFinishedRaces,TotalRaces
0,2009-03-29,Australian Grand Prix,18,British,19/01/1980,Jenson,Button,1,1.0,15.0,GB,Brawn,232.0,77.0,309
15,2009-04-19,Chinese Grand Prix,20,German,03/07/1987,Sebastian,Vettel,1,1.0,47.0,DE,Red Bull,167.0,32.0,199
62,2009-07-12,German Grand Prix,17,Australian,27/08/1976,Mark,Webber,1,1.0,9.0,AU,Red Bull,158.0,59.0,217
71,2009-07-26,Hungarian Grand Prix,1,British,07/01/1985,Lewis,Hamilton,4,1.0,62.0,GB,McLaren,183.0,25.0,208
133,2009-08-23,European Grand Prix,22,Brazilian,23/05/1972,Rubens,Barrichello,3,1.0,11.0,BR,Brawn,224.0,102.0,326
144,2009-08-30,Belgian Grand Prix,8,Finnish,17/10/1979,Kimi,RÌ_ikkÌ¦nen,6,1.0,20.0,FI,Ferrari,208.0,65.0,273
164,2008-04-06,Bahrain Grand Prix,13,Brazilian,25/04/1981,Felipe,Massa,2,1.0,11.0,BR,Ferrari,225.0,46.0,271
175,2008-06-08,Canadian Grand Prix,9,Polish,07/12/1984,Robert,Kubica,2,1.0,1.0,PO,BMW Sauber,63.0,13.0,76
176,2008-08-03,Hungarian Grand Prix,5,Finnish,19/10/1981,Heikki,Kovalainen,2,1.0,1.0,FI,McLaren,89.0,23.0,112
177,2008-09-28,Singapore Grand Prix,4,Spanish,29/07/1981,Fernando,Alonso,15,1.0,32.0,SP,Renault,233.0,60.0,293
209,2006-03-19,Malaysian Grand Prix,21,Italian,14/01/1973,Giancarlo,Fisichella,1,1.0,3.0,IT,Renault,157.0,74.0,231
212,2006-04-23,San Marino Grand Prix,30,German,03/01/1969,Michael,Schumacher,1,1.0,91.0,DE,Ferrari,238.0,70.0,308
303,2004-05-23,Monaco Grand Prix,15,Italian,13/07/1974,Jarno,Trulli,1,1.0,1.0,IT,Renault,162.0,94.0,256
304,2003-03-09,Australian Grand Prix,14,British,27/03/1971,David,Coulthard,11,1.0,13.0,GB,McLaren,165.0,82.0,247
317,2003-06-29,European Grand Prix,23,German,30/06/1975,Ralf,Schumacher,3,1.0,6.0,DE,Williams,118.0,62.0,180
323,2001-07-15,British Grand Prix,57,Finnish,28/09/1968,Mika,HÌ_kkinen,2,1.0,20.0,FI,McLaren,98.0,67.0,165
343,1999-03-07,Australian Grand Prix,56,British,10/11/1965,Eddie,Irvine,6,1.0,4.0,GB,Ferrari,82.0,65.0,147
347,1999-06-27,French Grand Prix,49,German,18/05/1967,Heinz-Harald,Frentzen,5,1.0,3.0,DE,Jordan,89.0,70.0,159
350,1999-09-26,European Grand Prix,65,British,25/06/1964,Johnny,Herbert,14,1.0,3.0,GB,Stewart,82.0,83.0,165
353,1998-08-30,Belgian Grand Prix,71,British,17/09/1960,Damon,Hill,3,1.0,22.0,GB,Jordan,74.0,48.0,122
375,1997-03-30,Brazilian Grand Prix,35,Canadian,09/04/1971,Jacques,Villeneuve,1,1.0,11.0,CA,Williams,103.0,62.0,165
386,1997-07-27,German Grand Prix,77,Austrian,27/08/1959,Gerhard,Berger,1,1.0,10.0,AS,Benetton,115.0,95.0,210
396,1996-05-19,Monaco Grand Prix,44,French,02/09/1966,Olivier,Panis,14,1.0,1.0,FR,Ligier,95.0,63.0,158
397,1995-06-11,Canadian Grand Prix,55,French,11/06/1964,Jean,Alesi,5,1.0,1.0,FR,Ferrari,114.0,88.0,202
398,1994-11-13,Australian Grand Prix,95,British,08/08/1953,Nigel,Mansell,1,1.0,31.0,GB,Williams,91.0,101.0,192
429,1993-03-14,South African Grand Prix,117,French,24/02/1955,Alain,Prost,1,1.0,51.0,FR,Williams,137.0,65.0,202
480,1993-03-28,Brazilian Grand Prix,102,Brazilian,21/03/1960,Ayrton,Senna,3,1.0,41.0,BR,McLaren,97.0,65.0,162
521,1992-10-25,Japanese Grand Prix,119,Italian,17/04/1954,Riccardo,Patrese,2,1.0,6.0,IT,Williams,112.0,145.0,257
527,1991-06-02,Canadian Grand Prix,137,Brazilian,17/08/1952,Nelson,Piquet,8,1.0,23.0,BR,Benetton,116.0,91.0,207
550,1990-08-12,Hungarian Grand Prix,123,Belgian,13/07/1957,Thierry,Boutsen,1,1.0,3.0,BE,Williams,93.0,71.0,164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,1961-05-22,Dutch Grand Prix,476,German,04/05/1928,Wolfgang,von Trips,2,1.0,2.0,DE,Ferrari,15.0,13.0,28
859,1961-06-18,Belgian Grand Prix,403,American,20/04/1927,Phil,Hill,1,1.0,3.0,US,Ferrari,30.0,22.0,52
862,1961-07-02,French Grand Prix,394,Italian,25/12/1934,Giancarlo,Baghetti,12,1.0,1.0,IT,Ferrari,10.0,16.0,26
863,1961-10-08,United States Grand Prix,404,British,12/06/1930,Innes,Ireland,8,1.0,1.0,GB,Lotus-Climax,25.0,30.0,55
864,1960-05-30,Indianapolis 500,509,American,16/07/1928,Jim,Rathmann,2,1.0,1.0,US,Watson,8.0,4.0,12
865,1959-05-30,Indianapolis 500,449,American,10/01/1921,Rodger,Ward,6,1.0,1.0,US,Watson,3.0,9.0,12
866,1959-05-31,Dutch Grand Prix,347,Swedish,31/01/1930,Jo,Bonnier,1,1.0,1.0,SE,BRM,48.0,61.0,109
867,1959-07-05,French Grand Prix,479,British,25/02/1932,Tony,Brooks,1,1.0,6.0,GB,Ferrari,21.0,20.0,41
873,1958-05-18,Monaco Grand Prix,427,French,30/10/1917,Maurice,Trintignant,5,1.0,2.0,FR,Cooper,43.0,44.0,87
875,1958-05-30,Indianapolis 500,525,American,28/01/1926,Jimmy,Bryan,7,1.0,1.0,US,Epperly,6.0,3.0,9
876,1958-07-06,French Grand Prix,578,British,10/04/1929,Mike,Hawthorn,1,1.0,3.0,GB,Ferrari,32.0,16.0,48
879,1958-07-19,British Grand Prix,581,British,06/11/1931,Peter,Collins,6,1.0,3.0,GB,Ferrari,16.0,21.0,37
882,1957-01-13,Argentine Grand Prix,579,Argentine,24/06/1911,Juan,Fangio,2,1.0,24.0,AR,Maserati,44.0,14.0,58
906,1957-05-30,Indianapolis 500,611,American,13/07/1914,Sam,Hanks,13,1.0,1.0,US,Epperly,5.0,4.0,9
907,1956-01-22,Argentine Grand Prix,577,Italian,28/07/1924,Luigi,Musso,3,1.0,1.0,IT,Ferrari,14.0,12.0,26
908,1956-05-30,Indianapolis 500,559,American,06/01/1926,Pat,Flaherty,1,1.0,1.0,US,Watson,3.0,3.0,6
909,1955-05-30,Indianapolis 500,628,American,20/05/1926,Bob,Sweikert,14,1.0,1.0,US,Kurtis Kraft,3.0,2.0,5
910,1954-05-31,Indianapolis 500,657,American,13/12/1918,Bill,Vukovich,19,1.0,2.0,US,Kurtis Kraft,2.0,3.0,5
912,1954-07-17,British Grand Prix,498,Argentine,05/10/1922,JosÌ© FroilÌÁn,GonzÌÁlez,2,1.0,2.0,AR,Ferrari,19.0,10.0,29
914,1953-01-18,Argentine Grand Prix,647,Italian,13/07/1918,Alberto,Ascari,1,1.0,13.0,IT,Ferrari,22.0,14.0,36
927,1953-08-02,German Grand Prix,642,Italian,30/10/1906,Nino,Farina,3,1.0,5.0,IT,Ferrari,26.0,11.0,37
932,1952-05-18,Swiss Grand Prix,641,Italian,12/10/1906,Piero,Taruffi,2,1.0,1.0,IT,Ferrari,12.0,6.0,18
933,1952-05-30,Indianapolis 500,526,American,11/03/1930,Troy,Ruttman,7,1.0,1.0,US,Kuzma,4.0,5.0,9
934,1951-07-01,French Grand Prix,786,Italian,1898-06-09,Luigi,Fagioli,7,1.0,1.0,IT,Alfa Romeo,7.0,1.0,8
935,1950-05-30,Indianapolis 500,593,American,04/07/1918,Johnnie,Parsons,5,1.0,1.0,US,Kurtis Kraft,6.0,4.0,10
936,2012-04-15,Chinese Grand Prix,3,German,27/06/1985,Nico,Rosberg,1,1.0,23.0,DE,Mercedes,175.0,31.0,206
959,2012-05-13,Spanish Grand Prix,813,Venezuelan,09/03/1985,Pastor,Maldonado,1,1.0,1.0,VE,Williams,64.0,32.0,96
960,2014-06-08,Canadian Grand Prix,817,Australian,01/07/1989,Daniel,Ricciardo,6,1.0,5.0,AU,Red Bull,110.0,19.0,129
965,2016-05-15,Spanish Grand Prix,830,Dutch,30/09/1997,Max,Verstappen,4,1.0,3.0,NL,Red Bull,45.0,15.0,60
968,2017-04-30,Russian Grand Prix,822,Finnish,28/08/1989,Valtteri,Bottas,3,1.0,3.0,FI,Mercedes,88.0,10.0,98

### PLOT IT!

In [28]:
%matplotlib notebook
import seaborn as sns
import matplotlib.pyplot as plt

In [70]:
notation = tuple(zip(Winners['TotalRaces'], Winners['TotalWins'], Winners['forename']+' '+ Winners['surname']))

In [151]:
plt.figure(figsize=(10,8))

plt.box(on=None)

ax = plt.gca()
ax.grid(color='black', linestyle='-', linewidth=0.05)

for elements in notation:    
    plt.annotate(elements[2], xy=((elements[0]*0.015+elements[0]), (elements[1]*0.03+elements[1])), alpha = elements[1]/Winners['TotalWins'].max())
    plt.scatter(x=elements[0], y=elements[1], alpha = (elements[1]+30)/(Winners['TotalWins'].max()+30), s = 10*elements[1], c = 'red')
#sns.set(context='notebook', style='darkgrid', palette='deep', font='sans-serif', font_scale=1, color_codes=False, rc=None)
plt.gca().set_title('Racing performance of the F1 winners')#, fontstyle = 'italic')# , color='r')


plt.xlabel("Number of races")#, fontstyle = 'italic')# , color='r')
plt.ylabel("Victories")#, fontstyle = 'italic')#№ , color='r')

plt.savefig('Assignment4 visual', dpi=300, facecolor='w', edgecolor='w',
        orientation='portrait', papertype=None, format=None,
        transparent=False, bbox_inches=None, pad_inches=0.1,
        frameon=None)